# Generated by Django 3.2.6 on 2021-08-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('add_date', models.DateTimeField(verbose_name='дата загрузки: ')),
            ],
        ),
    ]
